#!/bin/sh
# Generate a runtime config file that is served by your web server
cat <<EOF > /app/dist/config.js
window.__ENV__ = {
  FIREBASE_API_KEY: "${FIREBASE_API_KEY}",
  FIREBASE_AUTH_DOMAIN: "${FIREBASE_AUTH_DOMAIN}",
  FIREBASE_PROJECT_ID: "${FIREBASE_PROJECT_ID}",
  FIREBASE_STORAGE_BUCKET: "${FIREBASE_STORAGE_BUCKET}",
  FIREBASE_MESSAGING_SENDER_ID: "${FIREBASE_MESSAGING_SENDER_ID}",
  FIREBASE_APP_ID: "${FIREBASE_APP_ID}",
  FIREBASE_MEASUREMENT_ID: "${FIREBASE_MEASUREMENT_ID}",
  OPENAI_API_KEY: "${OPENAI_API_KEY}",
  OPENAI_BACKEND_URL: "${OPENAI_BACKEND_URL}"
};
EOF

# Execute the original command
exec "$@"